require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/distribution/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false

IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Naming/FileName:
  Exclude:
    - 'Gemfile'

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
