:concurrency: 5
:queues:
  - default
  - cron

:cron:
  monthly_reward:
    cron: "0 0 1 * *" # Runs at midnight on the 1st of every month
    class: MonthlyRewardWorker
    queue: cron

  birthday_reward:
    cron: "0 0 1 * *" # Runs at midnight on the 1st of every month
    class: BirthdayCoffeeRewardWorker
    queue: cron

  movie_ticket_reward:
    cron: "0 0 * * *"  # Run daily at midnight
    class: MovieTicketRewardWorker
    queue: cron
